//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yardkeeper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yardkeeper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_cloud_fog {
            get {
                object obj = ResourceManager.GetObject("conditions_cloud_fog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_cloud_frost {
            get {
                object obj = ResourceManager.GetObject("conditions_cloud_frost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_cloud_hail {
            get {
                object obj = ResourceManager.GetObject("conditions_cloud_hail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_cloud_lightning {
            get {
                object obj = ResourceManager.GetObject("conditions_cloud_lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_cloud_rain {
            get {
                object obj = ResourceManager.GetObject("conditions_cloud_rain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_cloud_snow {
            get {
                object obj = ResourceManager.GetObject("conditions_cloud_snow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_cloud_sun {
            get {
                object obj = ResourceManager.GetObject("conditions_cloud_sun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_cloud_sun_frost {
            get {
                object obj = ResourceManager.GetObject("conditions_cloud_sun_frost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_cloud_sun_rain {
            get {
                object obj = ResourceManager.GetObject("conditions_cloud_sun_rain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap conditions_sun {
            get {
                object obj = ResourceManager.GetObject("conditions_sun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;yardkeeper&gt;
        ///	&lt;yard&gt;
        ///		&lt;name&gt;My Backyard&lt;/name&gt;
        ///		&lt;length&gt;60&lt;/length&gt;
        ///		&lt;width&gt;40&lt;/width&gt;
        ///	&lt;/yard&gt;
        ///	&lt;sync&gt;1454550932&lt;/sync&gt;
        ///	&lt;telemetry&gt;
        ///		&lt;sensor&gt;
        ///			&lt;name&gt;Temperature&lt;/name&gt;
        ///			&lt;value&gt;25.8&lt;/value&gt;
        ///			&lt;suffix&gt;C&lt;/suffix&gt;
        ///		&lt;/sensor&gt;
        ///		&lt;sensor&gt;
        ///			&lt;name&gt;Dew point&lt;/name&gt;
        ///			&lt;value&gt;25.2&lt;/value&gt;
        ///			&lt;suffix&gt;C&lt;/suffix&gt;
        ///		&lt;/sensor&gt;
        ///		&lt;sensor&gt;
        ///			&lt;name&gt;Humidity&lt;/name&gt;
        ///			&lt;value&gt;54&lt;/value&gt;
        ///			&lt;suffix&gt;%&lt;/suffix&gt;
        ///		&lt;/sensor&gt;
        ///		&lt;sensor&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sensors {
            get {
                return ResourceManager.GetString("sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap telemetry_barometer {
            get {
                object obj = ResourceManager.GetObject("telemetry_barometer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap telemetry_humidity {
            get {
                object obj = ResourceManager.GetObject("telemetry_humidity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap telemetry_temperature {
            get {
                object obj = ResourceManager.GetObject("telemetry_temperature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
